version: '3.8'

services:
  api-server:
    build: ./api-server
    container_name: eureka
    restart: unless-stopped
    volumes:
      - ./api-server/logs:/app/logs
    ports:
      - "9000:9000"
    environment:
      - API_KEY=${API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}