# MCP Server Configuration

# Server configuration
server:
  host: "0.0.0.0"
  port: 5001

# Connectors configuration
connectors:
  jira:
    url: "https://your-jira-instance.atlassian.net"
    username: "your-username@example.com"
    token: ""
    max_results: 10
    query_fields:
      - "title"
      - "description"
      - "comments"

  confluence:
    url: "https://your-confluence-instance.atlassian.net"
    username: "your-username@example.com"
    token: ""
    max_results: 10
    spaces: []  # Leave empty to search all spaces

  s3:
    aws_access_key_id: ""
    aws_secret_access_key: ""
    region_name: "us-west-2"
    endpoint_url: ""  # Optional, for S3-compatible storage
    default_bucket: "documents"
    supported_formats:
      - "pdf"
      - "txt"
      - "docx"
      - "md"

# Default query settings
query:
  max_results: 10
  default_sources:
    - "jira"
    - "confluence"
    - "s3"

# Logging configuration
logging:
  level: "INFO"
  file: "logs/mcp-server.log"
  max_size_mb: 10
  backup_count: 5
